CREATE TABLE EMPLOYEE(
	EmpNo VARCHAR(200) PRIMARY KEY,
	EmpName VARCHAR(200) NOT NULL,
	BirthDay date NOT NULL,
	DeptNo SERIAL NOT NULL,
	MgrNo VARCHAR(200) NOT NULL,
	StartDate date NOT NULL,
	Salary money NOT NULL,
	Level int NOT NULL,
	CHECK (Level BETWEEN 1 AND 7),
	Status int NOT NULL,
	CHECK (Status BETWEEN 0 AND 2),
	Note VARCHAR NOT NULL
);


CREATE TABLE STATUS(
	Status int PRIMARY KEY,
	CHECK (Status BETWEEN 0 AND 2),
	TypeDetail VARCHAR(200) NOT NULL,
	FOREIGN KEY (Status) REFERENCES EMPLOYEE(Status)
);

CREATE TABLE SKILL(
	SkillNo SERIAL PRIMARY KEY,
	SkillName VARCHAR(200) NOT NULL,
	Note VARCHAR NOT NULL
);

CREATE TABLE EMP_SKILL(
	EmpNo VARCHAR(200) NOT NULL,
	SkillNo SERIAL,
	SkillLevel int NOT NULL,
	CHECK (SkillLevel BETWEEN 1 AND 3),
	RegDate date NOT NULL,
	Description VARCHAR NOT NULL,
	PRIMARY KEY (EmpNo, SkillNo),
	FOREIGN KEY (EmpNo) REFERENCES EMPLOYEE(EmpNo),
	FOREIGN KEY (SkillNo) REFERENCES SKILL(SkillNo),
);

CREATE TABLE DEPARTMENT(
	DeptNo SERIAL PRIMARY KEY,
	DeptName VARCHAR(200) NOT NULL,
	Note VARCHAR NOT NULL
);

--Q2
ALTER TABLE EMPLOYEE ADD CONSTRAINT df_MgrNo DEFAULT 0 FOR MgrNo;
ALTER TABLE EMPLOYEE ADD CONSTRAINT df_Status DEFAULT 0 FOR Status;
ALTER TABLE EMPLOYEE ADD COLUMN Email VARCHAR(200) NOT NULL UNIQUE DEFAULT(0);

--Q3
ALTER TABLE EMPLOYEE ADD CONSTRAINT fk_DeptNo FOREIGN KEY (DeptNo) REFERENCES DEPARTMENT(DeptNo);

ALTER TABLE EMP_SKILL DROP COLUMN Description;

--Q4

CREATE VIEW EMPLOYEE_TRACKING AS
SELECT EmpNo, EmpName, Level
FROM EMPLOYEE
WHERE Level BETWEEN 3 AND 5;

SELECT * FROM EMPLOYEE_TRACKING;
